### ISSUE TITLE
server down?

### ISSUE THREAD

**Issue by ReNardier** [yewtudotbe/invidious-custom#70]
did something happen?

**Comment by unixfox** [comment]
oracle cloud terminated my two accounts, for now I do not know when I'll be able to fully restore the service.
not even sure if I'll continue using oracle cloud

**Comment by ReNardier** [comment]
oh, with this and the trouble youtube is making, things are certainly not going well, i'll close the issue and let you handle things, best of luck and have a good day

**Comment by ReNardier** [comment]
reopened, sorry, i didn't see that you had pinned it

**Comment by evanferrao** [comment]
> oracle cloud terminated my two accounts, for now I do not know when I'll be able to fully restore the service. not even sure if I'll continue using oracle cloud

By any chance were you using the “Free Tier” resources w/o upgrading to “Pay As-You-Go”? Oracle seems to terminate accounts that do not upgrade to pay-as-you-go after some months of lingering on the free tier. It happened to 3 of my friends. For now, I've upgraded my oracle accounts by adding a spare credit card with all transactions disabled, so they can't bill me even if they wanted to.

**Comment by evanferrao** [comment]
> I did try again to recreate a new account but that didn't work.

My friends had issues creating accounts initially too. Since your previous account is terminated, you'll have to make a new one using a different IP (preferably mobile data, as its dynamic). Oracle kept declining my friends card even though it was valid, at the end he wrote an email to oracle support and they manually whitelisted his email and told him to try again after 3 days. It worked.

 > I did try a while ago to upgrade to PAYG but my credit card didn't work for some reason.
 
If you do manage to make an account, I can give my credit card info to add for PAYG. I plan to replace the card by the end of july as the physical card is in very poor condition (The plastic has literally peeled off). The card will be blocked soon, so its not much of an issue for me (The transactions also are limited to $5 each for security).

**Comment by Windows81** [comment]
Seems to be working again.

**Comment by unixfox** [comment]
I just recently restored the service yewtu.be.

You can read here what happened: https://gist.github.com/yewtudotbe/c16a69ddad88a37c2a364a5ff5359197
