### ISSUE TITLE
Consistent HTTP 429 from yewtu.be (+ redirect error)

### ISSUE THREAD

**Issue by forthrin** [yewtudotbe/invidious-custom#79]
**Describe the bug**
Consistent HTTP 429 errors on yewtu.be when using mpv with yt-dl hook.

**Steps to Reproduce**
1. `mpv https://yewtu.be/watch?v=r6sGWTCMz2k`

**Logs**
```
[ffmpeg] https: HTTP error 429 Too Many Requests
Failed to open https://www.yewtu.be/watch?v=XUto8p6fzNc.
```

**Additional context**
- mpv logs unfortunately don't say which request they make, even at msg-level=all=debug
- Never happened until a few days ago.
- Does not happen with eg. invidious.protokolla.fi, but that server sadly responds much slower.
- While testing, noticed the server also has an erroneous redirect.

```
$ curl --head 'https://www.yewtu.be/watch?v=XUto8p6fzNc'
HTTP/1.1 301 Moved Permanently
Location: https://yewtu.be/watch?v=XUto8p6fzNc?v=XUto8p6fzNc
```

**Comment by unixfox** [comment]
Unfortunately I only allow real browsers to use my instance, software like mpv are not real browsers. This due to filtering abuse and a software like mpv look too much like "a bot".

If you are looking for a way to use mpv with invidious I would suggest you to try other instances: https:/instances.invidious.io or install invidious locally on your computer: https://docs.invidious.io/installation/

**Comment by unixfox** [comment]
>     1. What kind of unwanted traffic hits the server, and what percentage of total traffic does this constitute?

It's too complicated to calculate, you can't always be certain if a request is malicious or not. From my time with dealing with bots, there is enough traffic to value the blockage based on certain rules that unfortunately block mpv.

Nowadays I do have less time for invidious, well I want to spend more time on others things. So these rules may be very harsh for my users and I sincerely apologize, but I want the piece of mind of not having to spend too much time on maintaining my instance.

That's also why, I don't say it out loud, I made the decision to not turn back on the registrations. That was also causing me too much trouble.

I would prefer to keep my instance in a state where 95% of people are happy with it, instead of maybe burning out due to having to support the remaining 5%.

>     2. How could mpv/FFmpeg be configured to be sufficiently distinguishable from unwanted traffic?

That's not possible, mpv is not a full browser, it's just a basic tool that will always look very similar to tools that can be used for bots like curl, HTTP libraries in various languages and so on.

**Comment by forthrin** [comment]
I am happy to hear you have your personal happiness and well-being as your first priority. Enough people burn out from failing the Pareto principle.
