### ISSUE TITLE
Instance down

### ISSUE THREAD

**Issue by 3hr80FEZwlir** [yewtudotbe/invidious-custom#93]
What's wrong? Instance is offline for few days already...

**Comment by unixfox** [comment]
My registrar blocked my domain due to a "false" abuse report.

There is an ongoing progress trying to unblock my domain. It was unblock at the time of me writing.

Here is the full conversation of me trying to unblock my domain:

![image](https://github.com/yewtudotbe/invidious-custom/assets/4016501/fccd85b0-4f6a-4d58-a250-67be1ea0b43f)
![image](https://github.com/yewtudotbe/invidious-custom/assets/4016501/44cf0548-2e50-42eb-bab7-6af40b3f65d4)
![image](https://github.com/yewtudotbe/invidious-custom/assets/4016501/09668939-b402-4058-b6d1-5da9cb662502)
![image](https://github.com/yewtudotbe/invidious-custom/assets/4016501/ad96222c-e35c-47bf-937f-8712ac2a42a0)
![image](https://github.com/yewtudotbe/invidious-custom/assets/4016501/ce8d8911-7caf-45c0-a8c0-d73b364109e6)
![image](https://github.com/yewtudotbe/invidious-custom/assets/4016501/9bedeccb-0a71-466b-a923-915c5bfb85a3)
![image](https://github.com/yewtudotbe/invidious-custom/assets/4016501/b548975c-56a7-4ec2-bc2c-b7ea706c37e5)

**Comment by BangDroid** [comment]
I'm assuming South Ark Weather channel being not blocked on this instance is intentional? Not saying it should be but it's what they wanted.

The registrar (or at least the support) seem to not understand that you're not hosting or infringing anyone's rights, it's all just YouTube. Looks as if someone at South Ark Weather doesn't understand either and filed the complaint. They're abusing the abuse system by not understanding what they're seeing!

**Comment by unixfox** [comment]
I'm going to move to another registrar that understand what is invidious, don't worry it's an issue I know I have to deal with.
